### ISSUE TITLE
How to get a transaction per second graph ？

### ISSUE THREAD

**Issue by matrix-2022** [OPMDG/opmdg.github.io#1]
How to get a transaction per second graph ？I want to see TPS of two specified databases in a graph for comparison.

Tank you!

**Comment by rjuju** [comment]
Hi,

We are currently working on a new probe for that in check_pgactivity project. This probe will allow having a transaction per second, commit per second, rollback per second and commit ratio metrics, and all those per database. We'll let you know when this new probe will be finished.

Regards.

**Comment by rjuju** [comment]
The commit_ratio probe has been added long time ago (https://github.com/OPMDG/check_pgactivity/commit/2c20fcb485b161ec14add155fed878e203e92955), sorry I forgot to keep you updated.

You can check its documentation on http://opm.readthedocs.io/probes/check_pgactivity.html#services.

Regards.
